### ISSUE TITLE
Different host organism

### ISSUE THREAD

**Issue by biseiohkawara** [barricklab/ostir#8]
In original RBS calculator (web tool version, Predict Mode), we can select the other host organisms. Can we do it with ostir program?

**Comment by croots** [comment]
Its possible, but your results may vary. OSTIR is [calibrated](https://github.com/barricklab/ostir/tree/master/calibration) on _E. coli_ fluorescence measurements. It will spit out predictions that it thinks are _E. coli_ RBS's. If your organism's translation initiation process is closely related to _E. coli_, you might get a result that works without re-calibration. You can change the anti Shine-Dalgarno sequence using the `-a` flag, which might help improve predictions if there's a difference.

There's [a conference abstract](https://publ.icgbio.ru/wp-content/uploads/2022/07/580-581.pdf) out there that claims they used this tool to slightly improve RNA as a signal of protein abundance in a variety of prokaryotes, but I haven't actually seen the study so I can't comment much beyond that.

**Comment by croots** [comment]
Let me know if you have any further questions. Otherwise, closing this issue as resolved.

Future contributions with calibration data from non _E. coli_ model organisms welcome from any onlookers.
